### PR TITLE
Add glob2 condition

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks @isuruf. Should we mark the old build as broken?

**Comment by isuruf** [comment]
Sure.

**Comment by jakirkham** [comment]
Have done this. Can you please verify that I've done this correctly?

**Comment by isuruf** [comment]
Perfect. Thanks

**Pull request merged**
