### PR TITLE
Rebuilding for Python 3.12 support

### PR DESCRIPTION
**Pull request by kenodegard**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kenodegard** [comment]
@conda-forge-admin, please rerender

**Comment by kenodegard** [comment]
@conda-forge-admin, please rerender

**Comment by kenodegard** [comment]
Python 3.12 support is blocked by `py-lief` (missing Python 3.12 support)

cc @conda-forge/lief

**Comment by h-vetinari** [comment]
See https://github.com/conda-forge/lief-feedstock/pull/42

**Comment by h-vetinari** [comment]
FWIW, it would be possible to test with the new lief builds by adding:
```
channel_sources:
  - conda-forge/label/lief_rc,conda-forge
```
to CBC and rerendering.

**Pull request merged**
