### PR TITLE
conda-build v3.18.11

### PR DESCRIPTION
**Pull request by msarahan**
Merge only after success.

This pull request was auto-generated by [rever](https://regro.github.io/rever-docs/)

### CODE REVIEW

**Comment by msarahan** [comment]
@conda-forge-admin please rerender

**Comment by jakirkham** [comment]
Could we please add `requests` as a dependency (even though it is implicitly required through Conda)? Noticing that it is listed [here]( https://github.com/conda/conda-build/blob/9cdeea385d637f2121c397af64f900504c05b798/setup.py#L17 ).

**Comment by msarahan** [comment]
Push to my branch if you want. I'm done for the weekend.

**Comment by jakirkham** [comment]
Was just about to, but looks like CJ beat me. Did submit it upstream though ( https://github.com/conda/conda-build/pull/3792 ). 😉

**Comment by jakirkham** [comment]
Thanks @msarahan! 😄

**Pull request merged**
