### PR TITLE
Bump 2.0.12

### PR DESCRIPTION
**Pull request by jakirkham**
Closes https://github.com/conda-forge/conda-build-feedstock/pull/6

Based off of @jjhelmus's PR ( https://github.com/conda-forge/conda-build-feedstock/pull/6 ) and @msarahan's PR ( https://github.com/conda-forge/conda-build-feedstock/pull/5 ) before that.

Bumps the version to 2.0.12 ~~and includes Python 3.6~~. Will bump to 2.1.0 after.

### CODE REVIEW

**Comment by jakirkham** [comment]
Failing because Python 3.6 is not fully supported yet. Maybe best to just to skip it until later?

**Comment by jjhelmus** [comment]
I'm not seeing a Python 3.6 build of `conda-build` in the  `defaults` channel yet.  I'm fine skipping those builds.

**Comment by jakirkham** [comment]
Thanks @jjhelmus. Have disable Python 3.6 for now. FWIW am trying to get the dependencies rebuilt for Python 3.6, but it will take some more time.

**Comment by jakirkham** [comment]
Looks like this is passing. Anything else?

**Comment by jjhelmus** [comment]
LGTM.  I don't have the merge bit on this feedstock but approve the merging of this!

**Comment by jakirkham** [comment]
> I don't have the merge bit on this feedstock but approve the merging of this!

Feel free to add yourself as a maintainer. Will happily merge. 👍

**Comment by jakirkham** [comment]
Thanks @msarahan.

**Comment by jakirkham** [comment]
Bumping to `2.1.1` in PR ( https://github.com/conda-forge/conda-build-feedstock/pull/8 ).

**Pull request merged**
