### PR TITLE
Update conda-build to 2.1.2

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Could someone with access rights please restart the failing Travis job?

**Comment by ocefpaf** [comment]
> Could someone with access rights please restart the failing Travis job?

Done!

**Comment by nicoddemus** [comment]
Thanks @ocefpaf!

**Comment by msarahan** [comment]
Thanks @nicoddemus and @ocefpaf - especially @nicoddemus for his help on the 2.1.2 release.

**Comment by jakirkham** [comment]
Awesome. Thanks all. 👏

**Comment by nicoddemus** [comment]
👍 😄

**Pull request merged**
