### PR TITLE
conda-build v3.18.2

### PR DESCRIPTION
**Pull request by msarahan**
Merge only after success.

This pull request was auto-generated by [rever](https://regro.github.io/rever-docs/)

### CODE REVIEW

**Comment by ocefpaf** [comment]
Does this release addresses https://github.com/conda/conda-build/issues/3514?

@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
Why is `ClircleCI` still active here?

**Comment by msarahan** [comment]
I'm not sure.  Sorry, I lost track of that one.  It should at least fix the tests not being activated.

I can tag a new release later today.  The main purpose of this release was fixing the indexing stuff for the new format.

**Comment by msarahan** [comment]
@isuruf seems like that isn't available yet?

**Comment by ocefpaf** [comment]
Looks like the CI for `lief` failed on master b/c of the time limit (at 99%!)

https://travis-ci.org/conda-forge/lief-feedstock

I restarted the job in case you want to wait for it.

**Comment by ocefpaf** [comment]
`lief` was uploaded. Closing and re-open to toggle the CIs here.

**Comment by msarahan** [comment]
Thanks @isuruf and @ocefpaf - glad to see this all working.  Merging.

**Pull request merged**
