### PR TITLE
Enable ripgrep for speedup on all architectures

### PR DESCRIPTION
**Pull request by dbast**
It is now also available on linux aarch64 and ppc64le.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

It is now also available on linux aarch64 and ppc64le.

### CODE REVIEW

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks @dbast! LGTM

**Comment by mingwandroid** [comment]
Are we building our own rust compilers now?

**Comment by dbast** [comment]
Rust is afaik a repack, see https://github.com/conda-forge/rust-feedstock/blob/master/recipe/meta.yaml

ripgrep we build ourself on conda-forge via that repacked rust.

**Comment by CJ-Wright** [comment]
This PR seems to have potentially broken conda-build? The autotick bot is failing with a conda-build error since two days ago https://circleci.com/gh/regro/circle_worker/10834

**Comment by isuruf** [comment]
No, it's not. This hack doesn't work anymore https://github.com/regro/circle_worker/blob/73e82f586a8e3c8fad0196c31058abe9ccab281a/.circleci/config.yml#L33-L34

**Comment by CJ-Wright** [comment]
Is it not needed, or is some other hack required?

**Comment by isuruf** [comment]
It is not needed. The hack was using `libarchive.so` from root env, but now that conda-package-handling 1.6.0 removed that, root env doesn't have `libarchive.so`. I don't know why it was forced like that. not setting that variable should pick up `libarchive.so` from the run env.

**Pull request merged**
