### PR TITLE
Update to 3.4.1

### PR DESCRIPTION
**Pull request by isuruf**
cc @msarahan

### CODE REVIEW

**Comment by msarahan** [comment]
is this ready to be merged?  I mean, are we ready to deal with whatever consequences come from merging it?

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by msarahan** [comment]
Thanks @isuruf - merging.

**Comment by jakirkham** [comment]
Did we already pin `conda-build` in `staged-recipes`? If not, this will break feedstock creation.

**Comment by isuruf** [comment]
Yes, https://github.com/conda-forge/staged-recipes/blob/master/.travis_scripts/create_feedstocks#L33

**Comment by jakirkham** [comment]
Great, thanks @isuruf!

**Comment by jdblischak** [comment]
@isuruf Since this PR was merged, does that mean the transition to conda-build 3 will happen soon? What is the plan for announcing this big change to the conda-forge community? I have already reviewed multiple recipes that had issues because the submitters installed conda-build from the conda-forge channel (and now it's version 3).

**Comment by isuruf** [comment]
>  Since this PR was merged, does that mean the transition to conda-build 3 will happen soon? What is the plan for announcing this big change to the conda-forge community?

Yes. It'll happen soon.

**Comment by jdblischak** [comment]
> What is the plan for announcing this big change to the conda-forge community?

@isuruf I just learned that the new version of conda-smithy was released a few days ago, completing the transition to conda-build 3. I never saw any official announcement of this big change. Please let me know if there is anything I can do to help the transition (e.g. updating documentation).

**Comment by msarahan** [comment]
The larger change going on behind the scenes is switching to the new compilers that Anaconda provides.  That's a big rebuild effort.  There's some info at https://github.com/AnacondaRecipes/AnacondaRecipesSync and more discussion at https://github.com/conda-forge/boost-cpp-feedstock/issues/25

It would be very helpful for you to clone that AnacondaRecipesSync repo:

```git clone --recursive https://github.com/AnacondaRecipes/AnacondaRecipesSync``` and try re-rendering and locally building recipes that you care about using the recipes there.  If you find issues, please report them on the corresponding feedstock at https://github.com/AnacondaRecipes.  We don't want to overload the CI's with too much rebuild work until we're more confident that the recipes are (mostly) good.

Note that you should probably do these in dependency order.  I will paste an attempt at that order in a gist later today and post back here.

We are rebuilding these too, but more eyes testing the process will be helpful, especially since you all are new to the new tools and will flush out weak points that we just got used to or haven't seen yet.

**Comment by jakirkham** [comment]
Guess people could use the [`compute_build_graph.py`]( https://github.com/conda-forge/staged-recipes/blob/master/.ci_support/compute_build_graph.py ) script to help build several in topo order.

**Comment by msarahan** [comment]
Yep, that's exactly what I'm running it through (but driven by c3i for doing the different platforms).  Taking quite a while because rendering is so slow (my fault, of course), but I'll have a good build order on all the different platforms later today.

**Comment by msarahan** [comment]
Build orders: https://github.com/AnacondaRecipes/AnacondaRecipesSync/issues/1

computed for linux, but other platforms should probably be able to follow the same

**Pull request merged**
