### PR TITLE
update to version 2.0.11

### PR DESCRIPTION
**Pull request by jjhelmus**
Based upon work by @msarahan in PR #5

### CODE REVIEW

**Comment by jakirkham** [comment]
As mentioned by @msarahan in this [comment]( https://github.com/conda-forge/conda-build-feedstock/pull/5#issuecomment-243150304 ), we need to update to `conda-build` version `2.0.x` to build the new version. So I think we are going to have to hack the CI scripts or something to do that.

**Comment by jjhelmus** [comment]
> As mentioned by @msarahan in this comment, we need to update to conda-build version 2.0.x to build the new version

I don't think this is necessarily true.  I think the failing tests in PR #5 were due to incorrect entry points and missing requirements not the version of `conda-build`.  Would appreciate if @msarahan could comment on this.

**Comment by msarahan** [comment]
If tests pass here, things should be fine. I thought you needed conda build 2 to build it correctly, but I'm happy to be proven wrong.

**Comment by jakirkham** [comment]
Ok. Well it appears to pass. Are there other tests it should have? Or are we ready to merge this?

FWIW we will still be using `conda-build` version 1.21.14 even after merging this as it is still pinned, but this will give us the opportunity to test it out on the long prefix rebuild. If it does have problems in those cases, we can always pull it and fix it up in a new PR.

**Comment by jakirkham** [comment]
Could we bump this to `2.0.12`? Otherwise (hearing no complaints) would like to click the merge button. 😄

**Comment by jakirkham** [comment]
Went ahead and bumped it in PR ( https://github.com/conda-forge/conda-build-feedstock/pull/7 ).

**Pull request closed without merging**
