### PR TITLE
test conda-build setuptools entry points

### PR DESCRIPTION
**Pull request by msarahan**

### CODE REVIEW

**Comment by msarahan** [comment]
I have run into the issue that @takluyver brought up with pip entry point executables needing some kind of binary prefix replacement.  I will look into this tomorrow.

**Comment by takluyver** [comment]
IIRC, the structure of the exe launchers is like this:

- Compiled Windows executable
- UTF-8 encoded shebang pointing to the Python interpreter
- Zip file containing the Python code to run

**Comment by msarahan** [comment]
Thanks @takluyver, that is consistent with what I'm seeing.  I need to enable binary prefix replacement on Windows in both conda and conda-build, but then it looks like things should just work.  Fingers crossed.

**Comment by msarahan** [comment]
PR at https://github.com/conda/conda/pull/3224 - minor changes also required in conda-build to ensure that case sensitivity does not mask binary files with prefixes on windows: https://github.com/conda/conda-build/pull/1171

I'll ping you again when the dust settles, @takluyver, to see where we stand with flit.

**Comment by msarahan** [comment]
@takluyver between conda-build 2.0.2 and conda 4.2.x, this has a pretty good chance of working.  Care to give it a try and let me know how it goes?

**Comment by jakirkham** [comment]
Do we still need this or should we close it out?

**Comment by msarahan** [comment]
Thanks

**Pull request closed without merging**
