### PR TITLE
Update to 3.23.2

### PR DESCRIPTION
**Pull request by kenodegard**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Xref https://github.com/conda/conda-build/issues/4617
Corrects `zstd_compression_level` issue: https://github.com/conda/conda-build/pull/4650

### CODE REVIEW

**Comment by kenodegard** [comment]
@conda-forge-admin, please rerender

**Review by mbargull — APPROVED** [review]
Nothing really changed dep-wise in the last 2 weeks, so all good to go.

Thanks Ken!

**Comment by mbargull** [comment]
Just one of the Windows builds failed because of OOM. I'll just merge and restart CI as need afterwards. (I.e., no need to switch to .tar.bz2 if most builds work the first time.)

**Comment by jakirkham** [comment]
Looks like one of the builds [failed on `main` for Windows Python 3.11]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=621052&view=logs&j=533b006e-c27f-58a3-8df4-b5a79e785988&t=dccf4699-a398-5507-50c7-f61f6dad5a20 ). Also due to the OOM error.

However since the build environment uses Python 3.9 and that Windows build completed successfully, restarting should fix it. Going to try restarting the failed build

**Comment by jakirkham** [comment]
Hmm...seeing [`conda-build` version `3.22.0` still used in the job]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=621052&view=logs&j=71a23920-152a-53ca-00d8-b45290d07ed2&t=68dbc64e-b9ea-5236-8ff2-c2ac4825e498&l=36 ). Is `conda-build` pinned somewhere?

**Comment by mbargull** [comment]
I'll update the boa feedstock.

**Comment by jakirkham** [comment]
Ah ok. Thanks Marcel! 🙏

For [reference `conda-build` is pinned in `boa`]( https://github.com/conda-forge/boa-feedstock/blob/dae38b0feadbdc44fa13bc6f88d85ba20874528c/recipe/meta.yaml#L29 ).

**Comment by jakirkham** [comment]
Filing a `boa` feedstock issue to track ( https://github.com/conda-forge/boa-feedstock/issues/58 )

**Pull request merged**
