### PR TITLE
Bump to version 24.3.0

### PR DESCRIPTION
**Pull request by beeankha**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beeankha** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Hey @beeankha, I picked your commit into #221 and layered some necessary fixes on top. Feel free to pick them into your PR if you want (I wanted to avoid pushing into yours without asking).

**Comment by beeankha** [comment]
Hi @h-vetinari , thanks so much for picking my commit into #221 ! Since that PR looks closer to being merge-able, we can close this one and continue with #221 if that's easiest/most straightforward. 👍

**Comment by beeankha** [comment]
Closing due to #221 looking like it's passing now

**Pull request closed without merging**
