### PR TITLE
Release 2.1.7

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by jakirkham** [comment]
Could you please take a look @msarahan? It doesn't look like any of the dependencies change, but am not sure.

**Comment by msarahan** [comment]
Should be fine, except that @ilanschnell pointed out an odd issue here: https://github.com/conda/conda-build/issues/1850

Not sure how much of a concern that is for you.

**Comment by jakirkham** [comment]
Given what we now know about the issue, I'm not worried about it. It seems all feedstocks using `run_test.py` are using `print` as a function.

ref: https://github.com/search?utf8=✓&q=org%3Aconda-forge++filename%3Arun_test.py+print&type=Code&ref=searchresults

**Comment by msarahan** [comment]
Great. Merging.

**Comment by jakirkham** [comment]
Thanks Mike.

**Comment by jakirkham** [comment]
Seems we are running into the same issue we have seen with other Python 2.7 uploads. Do you have any idea what is happening, Mike? Naively I would assume we provided something unacceptable to `env`, but we just pass `os.environ` and don't otherwise manipulate this. 😕 Are there some new environment variables being set that might cause this issue?

xref: https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/60

**Pull request merged**
