### PR TITLE
conda-build PR 4001

### PR DESCRIPTION
**Pull request by mbargull**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Adds https://github.com/conda/conda-build/pull/4001.
This gives me some trouble while batch processing recipes since `conda-build` catches `conda`'s `UnsatisfiableError` and turns it into a generic `RuntimeError` without this patch.

Since it's a really minor bug fix, I'd appreciate it, if we could get this in quickly.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please restart CI.

**Comment by jakirkham** [comment]
There seems to be an [unknown GitHub incident]( https://www.githubstatus.com/incidents/t0bf10rtnrgz ) being tracked.

**Comment by mbargull** [comment]
Thanks for checking @jakirkham!

**Comment by mbargull** [comment]
@conda-forge-admin, please restart CI.

**Comment by mbargull** [comment]
https://www.githubstatus.com/incidents/t0bf10rtnrgz is marked as resolved but still no dice here :/

**Comment by jakirkham** [comment]
Third try is a charm? 🍀 

@conda-forge-admin, please restart CI.

**Comment by jakirkham** [comment]
I think they marked that resolved too quickly. Seems like there is still some sort of webhook issue otherwise the bot would have done something.

**Comment by mbargull** [comment]
@conda-forge-admin, please restart CI.

**Comment by jakirkham** [comment]
@conda-forge-admin, please restart CI.

**Comment by jakirkham** [comment]
I've tried manually triggering this through Azure. Not sure that is working either. Could you please check if the org this is submitted from has Azure enabled?

**Comment by mbargull** [comment]
Just to test things out, I just now enabled Azure for https://github.com/mbargull-feedstocks/conda-build-feedstock . This does work fine on new commits: https://dev.azure.com/mbargull/mbargull-feedstocks/_build/results?buildId=3 .
(However, for PRs we'd run conda-forge's Azure Pipelines and as such forks don't have to enable Azure, of course.)

**Comment by jakirkham** [comment]
Not sure why it's not working. Trying to re-render in PR ( https://github.com/conda-forge/conda-build-feedstock/pull/143 ) in the hope that helps.

**Comment by mbargull** [comment]
Well, I also rerendered in this PR... But it seems you're more likeable than me :O -- at least according to the CI's preference ;P

**Comment by jakirkham** [comment]
Sort of. Asking the bot to re-render hasn't worked and the linter was MIA (at least until poked).

**Comment by mbargull** [comment]
Well, it did work somehow, finally. Thanks for your help @jakirkham, appreciated!

**Comment by mbargull** [comment]
@conda-forge/conda-build, anyone opposed to this change?
This is a small non-disruptive bug fix that would spare me from a good amount of trouble.

**Comment by scopatz** [comment]
It seems as though this hasn't been merged into conda-build yet

**Comment by mbargull** [comment]
@scopatz, I know and I am also not keen when people ask to include non-upstream-approved patches of still active projects.

I just don't expect upstream to react quickly on this issue since it apparently didn't affect Anaconda's and conda-forge's workflows much (otherwise it would've been fixed already -- or even replaced by less frail logic...).

I makes the ongoing rebuilds on Bioconda for the Python 3.8 adoption much much more laborsome!

**Comment by mbargull** [comment]
The patch has been merged upstream -> merging this too.

**Pull request merged**
