### PR TITLE
conda-build v3.18.8

### PR DESCRIPTION
**Pull request by jjhelmus**
Merge only after success.

This pull request was auto-generated by [rever](https://regro.github.io/rever-docs/)

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by jjhelmus** [comment]
This release includes conda/conda-build#3613 which should fix some (although not all) of the issue with `run_exports`.

**Comment by isuruf** [comment]
What do you mean by not all? If it is still problematic, is there a conda-build setting to go back to the old way?

**Comment by jjhelmus** [comment]
There are still issues if package variants express different `run_exports` as channeldata.json only captures a single `run_export` for each version.  There is no option at the moment to force the use of the information within the packages which was the behavior prior to 3.18.0.  I need to dig deeper for a complete fix.

**Comment by isuruf** [comment]
Ah, so our blas scheme will not work then? Where can I find this `channeldata.json` file for conda-forge?

**Comment by jjhelmus** [comment]
https://conda.anaconda.org/conda-forge/channeldata.json

**Comment by isuruf** [comment]
Looks like blas has the correct run_exports

**Pull request merged**
